export const people = [
  {
    'id': 1,
    'name': 'Ane',
    'age': 10,
    'dream': 'To become an astronaut',
  },
  {
    'id': 2,
    'name': 'Bent',
    'age': 20,
    'dream': 'To build his own software company',
  },
  {
    'id': 3,
    'name': 'Cecilie',
    'age': 30,
    'dream': 'To travel the world and help people in need',
  },
  {
    'id': 4,
    'name': 'Denis',
    'age': 40,
    'dream': 'To write a best-selling novel',
  },
  {
    'id': 5,
    'name': 'Erik',
    'age': 50,
    'dream': 'To retire and spend the rest of his days painting',
  },
  {
    'id': 6,
    'name': 'Finn',
    'age': 60,
    'dream': 'To design and build his own dream house',
  },
  {
    'id': 7,
    'name': 'Gustav',
    'age': 70,
    'dream': 'To live long enough to see his great-grandchildren grow up',
  },
  {
    'id': 8,
    'name': 'Hans',
    'age': 80,
    'dream': 'To see a world where peace and understanding reign',
  },
  {
    'id': 9,
    'name': 'Ib',
    'age': 90,
    'dream': 'To travel back in time and relive his favorite moments',
  },
  {
    'id': 10,
    'name': 'Jens',
    'age': 10,
    'dream': 'To become a famous chef',
  },
  {
    'id': 11,
    'name': 'Kurt',
    'age': 11,
    'dream': 'To become a professional soccer player',
  },
  {
    'id': 12,
    'name': 'Lars',
    'age': 12,
    'dream': 'To become a scientist and discover something new',
  },
  {
    'id': 13,
    'name': 'Mads',
    'age': 13,
    'dream': 'To become a successful businessman',
  },
  {
    'id': 14,
    'name': 'Nikolaj',
    'age': 14,
    'dream': 'To become a famous musician',
  },
  {
    'id': 15,
    'name': 'Ole',
    'age': 34,
    'dream': 'To become a digital nomad and travel the world',
  },
  {
    'id': 16,
    'name': 'Peter',
    'age': 41,
    'dream': 'To start his own charity and help people in need',
  },
  {
    'id': 17,
    'name': 'Quintus',
    'age': 64,
    'dream': 'To retire and spend the rest of his days sailing the seas',
  },
  {
    'id': 18,
    'name': 'Rasmus',
    'age': 34,
    'dream': 'To become a famous actor',
  },
  {
    'id': 19,
    'name': 'Søren',
    'age': 25,
    'dream': 'Søren s dream is to become the first person to set foot on Mars.',
  }];

